[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["python"]

[build.nixpacksConfig.python]
version = "3.11"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHONPATH = "/app:/app/webapp"
PYTHONUNBUFFERED = "1"